import { describe, expect, it } from "vitest";
import { createInitialState, dispatchKeys } from "../src/calc/machine.ts";
import { lcdResult } from "../src/ui/lcdModel.ts";
import type { KeyId } from "../src/calc/keys.ts";

function run(keys: KeyId[]) {
  return dispatchKeys(createInitialState(0), keys, 0);
}

describe("STAT goldens", () => {
  it("GT-ST-OFFICIAL-EX2 1-VAR FREQ mean=3 TARGET-OFFICIAL-DOC", () => {
    const s = run([
      "shift",
      "mode",
      "down",
      "4",
      "1",
      "mode",
      "3",
      "1",
      "1",
      "equals",
      "2",
      "equals",
      "3",
      "equals",
      "4",
      "equals",
      "5",
      "equals",
      "right",
      "up",
      "up",
      "up",
      "up",
      "up",
      "1",
      "equals",
      "2",
      "equals",
      "3",
      "equals",
      "2",
      "equals",
      "ac",
      "shift",
      "1",
      "4",
      "2",
      "equals",
    ]);
    expect(s.mode).toBe("STAT");
    expect(s.stat?.type).toBe("1-VAR");
    expect(s.stat?.phase).toBe("calc");
    expect(s.stat?.rows.slice(0, 5).map((r) => ({ x: r.x, freq: r.freq }))).toEqual([
      { x: "1", freq: "1" },
      { x: "2", freq: "2" },
      { x: "3", freq: "3" },
      { x: "4", freq: "2" },
      { x: "5", freq: null },
    ]);
    expect(lcdResult(s)).toBe("3");
  });

  it("GT-ST-OFFICIAL-EX3 ln X A=-3857.984 Fix 3 TARGET-OFFICIAL-DOC", () => {
    const s = run([
      "shift",
      "mode",
      "6",
      "3",
      "mode",
      "3",
      "2",
      "2",
      "0",
      "equals",
      "1",
      "1",
      "0",
      "equals",
      "2",
      "0",
      "0",
      "equals",
      "2",
      "9",
      "0",
      "equals",
      "right",
      "up",
      "up",
      "up",
      "up",
      "3",
      "1",
      "5",
      "0",
      "equals",
      "7",
      "3",
      "1",
      "0",
      "equals",
      "8",
      "8",
      "0",
      "0",
      "equals",
      "9",
      "3",
      "1",
      "0",
      "equals",
      "ac",
      "shift",
      "1",
      "1",
      "4",
      "shift",
      "1",
      "5",
      "1",
      "equals",
    ]);
    expect(s.stat?.type).toBe("ln X");
    expect(s.stat?.rows.slice(0, 4).map((r) => ({ x: r.x, y: r.y }))).toEqual([
      { x: "20", y: "3150" },
      { x: "110", y: "7310" },
      { x: "200", y: "8800" },
      { x: "290", y: "9310" },
    ]);
    expect(lcdResult(s)).toBe("-3857.984");
  });

  it("GT-ST-OFFICIAL-EX4 ln X x̂(-130)=4.861 Fix 3 TARGET-OFFICIAL-DOC", () => {
    const s = run([
      "shift",
      "mode",
      "6",
      "3",
      "mode",
      "3",
      "4",
      "2",
      "0",
      "equals",
      "1",
      "1",
      "0",
      "equals",
      "2",
      "0",
      "0",
      "equals",
      "2",
      "9",
      "0",
      "equals",
      "right",
      "up",
      "up",
      "up",
      "up",
      "3",
      "1",
      "5",
      "0",
      "equals",
      "7",
      "3",
      "1",
      "0",
      "equals",
      "8",
      "8",
      "0",
      "0",
      "equals",
      "9",
      "3",
      "1",
      "0",
      "equals",
      "ac",
      "neg",
      "1",
      "3",
      "0",
      "shift",
      "1",
      "5",
      "4",
      "equals",
    ]);
    expect(s.mode).toBe("STAT");
    expect(s.stat?.type).toBe("ln X");
    expect(lcdResult(s)).toBe("4.861");
  });
});
